#!/bin/bash

logger -p news.info "Running .xprofile"

/usr/bin/xscreensaver -nosplash &

if [[ -e ~/.Xmodmap ]]; then
    logger -p news.info "Xmodmapping..."
    /usr/bin/xmodmap ~/.Xmodmap
fi

# composite manager
if [[ -f /usr/bin/compton ]]; then
    /usr/bin/compton -b
fi

# use local i3 config, where available
if [[ ! -f "${HOME}/config/i3/merge_config.sh" ]]; then
    logger -p syslog.warning "Cannot find merge script for i3 config"
else
    bash "${HOME}/config/i3/merge_config.sh"
fi

#local changes
if [[ -f "${HOME}/.xprofile.local" ]]; then
    source "${HOME}/.xprofile.local"
fi

#wallpaper
if [[ -f "${HOME}/.fehbg" ]]; then
    sh "${HOME}/.fehbg"
fi
