#!/bin/sh

set -u

logger -p news.info "Running .xprofile"

LOGIN_CMD="i3"



if [[ -z ${1+x} ]] ; then
    logger -p syslog.warn "No login command was found. Falling back to default: ${LOGIN_CMD}"
else
    LOGIN_CMD="${1}"
fi
logger -p news.info "Preparing for session: \"${LOGIN_CMD}\""

if [[ "${LOGIN_CMD}" = i3 ]] ; then
    logger -p news.info "[+] Preparing i3 session..."
    logger -p news.info "[+] Starting xscreensaver"
    /usr/bin/xscreensaver -nosplash &
    if [[ -e ~/.Xmodmap ]] ; then
        logger -p news.info "Xmodmapping..."
        /usr/bin/xmodmap ~/.Xmodmap || true
    fi

    logger -p news.info "[+] Merging i3 config"
    # use local i3 config, where available
    if [[ ! -f "${HOME}/config/i3/merge_config.sh" ]] ; then
        logger -p syslog.warning "[!] Cannot find merge script for i3 config"
    else
        bash "${HOME}/config/i3/merge_config.sh" || true
    fi

    logger -p news.info "[!] Picom launch disabled due to Intel graphics bug"
    #logger -p news.info "[+] Starting picom"
    ## composite manager
    #if [[ -f /usr/bin/picom ]] ; then
    #    /usr/bin/picom -b
    #fi

    logger -p news.info "[+] Setting wallpaper"
elif [[ "${LOGIN_CMD}" = sway ]] ; then
    logger -p news.info "[+] Preparing sway session..."
    ## nothing for now
fi

#local changes
if [[ -f "${HOME}/.xprofile.local" ]] ; then
    logger -p news.info "[+] Found local profile. Sourcing..."
    source "${HOME}/.xprofile.local"
fi

set +u
